### ISSUE TITLE
扩展程序无法正常使用

### ISSUE THREAD

**Issue by baltam** [lxfater/BilibiliSummary#2]
超级棒的ai落地应用，点赞就完事了！然而折腾了一会用不了呢...
根据dalao的安装教程已经把程序安装成功了，并且加入到了扩展栏中，但是在使用过程中出现了一些问题：
![image](https://user-images.githubusercontent.com/25541578/221401947-92f3a245-e205-45ab-9a84-7a175cddbebf.png)
以为是chatgpt问题，然后重新登录了一次，不行
以为是浏览器问题，把edge换成了Chrome，也不行
是dalao没有把完整版放出来么，还是说是因为我某些设置没有做好呢，或者是说这个程序只是个demo，要想正常使用的话需要修改js代码呢，希望dalao有空的是帮忙解答！
![image](https://user-images.githubusercontent.com/25541578/221402117-3fadc2f3-e080-448b-91e1-1b9283b48710.png)

**Comment by lxfater** [comment]
给我点时间，我会发布一个稳定版本的，现在出现了非plus用户不能稳定使用的问题。

**Comment by baltam** [comment]
> 给我点时间，我会发布一个稳定版本的，现在出现了非plus用户不能稳定使用的问题。

好的，感谢感谢，dalao加油！顺便问一个问题：
```bash
Module '"./main-world"' has no exported member 'MainWorld'
```
![image](https://user-images.githubusercontent.com/25541578/221409971-426adc91-8b9e-4736-8179-22683a2b5b6c.png)
这里报错是什么原因造成的呢，应该如何解决呢？

**Comment by baltam** [comment]
根据chrome-extension的repository中的issue修改成功了，但是不稳定，期待dalao的更新~

**Comment by lxfater** [comment]
你想要测试新版吗？ @baltam

**Comment by baltam** [comment]
> 你想要测试新版吗？ @baltam

有这个想法，但是该如何测试呢

**Comment by lxfater** [comment]
> > 你想要测试新版吗？ @baltam
> 
> 有这个想法，但是该如何测试呢

已经更新，再release里面。
