### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by beianliu** [lxfater/BilibiliSummary#3]
1.支持使用自己的OpenAI API，而不是在另一个页面登录chatgpt账号。
2.有打包好的crx文件就更方便了。

辛苦了。

**Comment by lxfater** [comment]
你安心把你的账号和密码交给我吗？ @beianliu

**Comment by beianliu** [comment]
@lxfater 不动用户的密码不是最基本的吗？而且有限额

**Comment by lxfater** [comment]
那就不应该交给我，我也不需要你的用户和密码，而且理论上也没有限额。 @beianliu

**Comment by lxfater** [comment]
> https://glarity.app 就是这个的 B 站版嘛，我的建议是跟 glarity 一样，需要 api key 访问 apikey 是不限制地区的，网页登陆限制地区
> 
> 浏览器拓展保存的信息 != 允许信息发送至拓展作者服务器

apikey 真的很花钱，按字数来的,字幕有时候很多很难，使用免费的不好吗？而且apikey是方式是chatgpt3的。我花了好多天才调研出如何桥接这个chatgpt（gpt3.5）的api来。

当然你们愿意用apikey我也可以支持，后面我会开发的。

**Comment by beianliu** [comment]
@lxfater 
目前会高频率的提示需要重新登录chatgpt才能获取视频摘要,点击图标跳转登录。
apikey的话没这个问题，速度也会快很多。

费用的问题，给2个选择嘛，用免费还是官方的付费api个人选择问题。

另外从总结YouTube视频摘要来看，chatgpt3够用了。

**Comment by lxfater** [comment]
> @lxfater 
> 目前会高频率的提示需要重新登录chatgpt才能获取视频摘要,点击图标跳转登录。
> apikey的话没这个问题，速度也会快很多。
> 
> 费用的问题，给2个选择嘛，用免费还是官方的付费api个人选择问题。
> 
> 另外从总结YouTube视频摘要来看，chatgpt3够用了。
> 
> 

别把chatgpt窗口关闭了，应该能用一个小时。你确定你装的是1.0.0版本吗？

**Comment by beianliu** [comment]
确实是1.0.0。  不好意思是我的问题，把窗口关了。
