### ISSUE TITLE
依赖安装失败

### ISSUE THREAD

**Issue by DYDY233** [lxfater/BilibiliSummary#6]
node: 16.16.0 npm 8.11.0
"ai-bridge": "^1.0.3"
npm ERR! code ENOVERSIONS
npm ERR! No versions available for ai-bridge

**Comment by lxfater** [comment]
@DYDY233  更换为@lxfater/ai-bridge 目前源码版本和实际版本差距有点大，假如想使用的话，可以等待bug版本修复

**Comment by DYDY233** [comment]
了解，谢谢(´▽`)ﾉ
